### ISSUE TITLE
Issue with installing old drupal core.

### ISSUE THREAD

**Issue by ghost** [hussainweb/drupal-composer-init#2]
I need to install drupal  8.3, But When I tried that. It's not downloading all the files ( index.php, update.php and all the files in the doc root is missing, but directories are there)

**Comment by hussainweb** [comment]
@shafeequeaslam, I'll need more details to check this. I just tried this out by setting `drupal/core` to `~8.3.0` during the `drupal-init` command. Once I ran `composer install`, all of the files are created properly.

**Comment by nimoatwoodway** [comment]
In any case someone else step into this problem. I've forgotten to delete the composer.lock before reinstalling.
